spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
       - id: pensioner-detail-service
         uri: lb://PENSIONER-DETAIL-SERVICE
         predicates:
           - Path=/pensionerDetail/**
#         filters:
#             - AuthenticationFilter
#            - name: CicuitBreaker
#              args:
#                name: pensioner-detail-service
#                fallbackuri: forward:/pdFallBack 
      
       - id: process-pension
         uri: lb://PROCESS-PENSION-SERVICE
         predicates:
           - Path=/processPension/**
#         filters:
#           - AuthenticationFilter
#            - name: CicuitBreaker
#              args:
#                name: process-pension
#                fallbackuri: forward:/ppFallBack   
       - id: authentication
         uri: lb://AUTHORIZATION-SERVICE
         predicates:
           - Path=/authenticate
        
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost   
     
server:
  port: 9002
  

       
        
  
  
#jwt:
#  secret: testing
           
          
            